name: 更新 Sub-Store Docker 镜像并调用 API

on:
  schedule:
    - cron: '0 0 * * *' # 每天午夜 UTC 时间运行
  workflow_dispatch: # 允许手动触发

jobs:
  update-dockerfile-and-call-api:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码仓库
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 从 Docker Hub 获取最新的 http-meta 标签
        id: get_tag
        run: |
          LATEST_TAG=$(curl -s 'https://hub.docker.com/v2/repositories/xream/sub-store/tags/?page_size=100&name=http-meta' | \
          jq -r '.results | map(select(.name | endswith("-http-meta"))) | .[0].name')
          if [ -z "$LATEST_TAG" ]; then
            echo "获取最新的 http-meta 标签失败。"
            exit 1
          fi
          echo "最新的 http-meta 标签: $LATEST_TAG"
          echo "TAG=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: 更新 Dockerfile
        id: update_dockerfile
        run: |
          CURRENT_TAG=$(grep -oP 'xream/sub-store:\K[^"]+' Dockerfile)
          NEW_TAG="${{ steps.get_tag.outputs.TAG }}"
          echo "Dockerfile 中的当前标签: $CURRENT_TAG"
          echo "从 Docker Hub 获取的新标签: $NEW_TAG"

          if [ "$CURRENT_TAG" != "$NEW_TAG" ] && [ -n "$NEW_TAG" ]; then
            sed -i "s|xream/sub-store:$CURRENT_TAG|xream/sub-store:$NEW_TAG|g" Dockerfile
            echo "Dockerfile 已更新为新标签: $NEW_TAG"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "Dockerfile 已是最新版本或新标签无效。"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: 如果有更改则提交并推送
        if: steps.update_dockerfile.outputs.changed == 'true'
        id: commit_push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add Dockerfile
          git commit -m "更新 sub-store 至版本 ${{ steps.get_tag.outputs.TAG }}"
          git push https://x-access-token:${{ secrets.REPO_PAT }}@github.com/${{ github.repository }}.git HEAD:refs/heads/${{ github.ref_name }}
        env:
          REPO_PAT: ${{ secrets.REPO_PAT }}

      - name: 调用 Substore API 更新设置并备份
        if: steps.update_dockerfile.outputs.changed == 'true' && steps.commit_push.outcome == 'success'
        env:
          SUBSTORE_GIST_TOKEN: ${{ secrets.SUBSTORE_GIST_TOKEN }}
          SUBSTORE_API_ID: ${{ secrets.SUBSTORE_API_ID }} # 注入 API ID Secret
        run: |
          echo "等待3分钟，以便服务可能重启或更新..."
          sleep 180 # 3 分钟 = 180 秒

          echo "开始调用 Substore API 更新设置 (ID: $SUBSTORE_API_ID)..."
          curl "https://sub.xujw.dpdns.org/${SUBSTORE_API_ID}/api/settings" \
            -X 'PATCH' \
            -H 'accept: application/json, text/plain, */*' \
            -H 'accept-language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6' \
            -H 'content-type: application/json' \
            -H 'origin: https://sub.xujw.dpdns.org' \
            -H 'priority: u=1, i' \
            -H 'referer: https://sub.xujw.dpdns.org/my' \
            -H 'sec-ch-ua: "Microsoft Edge";v="137", "Chromium";v="137", "Not/A)Brand";v="24"' \
            -H 'sec-ch-ua-mobile: ?0' \
            -H 'sec-ch-ua-platform: "Windows"' \
            -H 'sec-fetch-dest: empty' \
            -H 'sec-fetch-mode: cors' \
            -H 'sec-fetch-site: same-origin' \
            -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36 Edg/137.0.0.0' \
            --data-raw '{"syncPlatform":"","githubUser":"kingxujw8@gmail.com","gistToken":"'"$SUBSTORE_GIST_TOKEN"'","defaultUserAgent":"","defaultProxy":"","defaultTimeout":"","cacheThreshold":""}' \
            --fail

          echo "调用 API 更新设置完成。"
          echo "开始调用 Substore API 备份数据 (ID: $SUBSTORE_API_ID)..."

          curl "https://sub.xujw.dpdns.org/${SUBSTORE_API_ID}/api/utils/backup?action=download" \
            -H 'sec-ch-ua-platform: "Windows"' \
            -H 'Referer: https://sub.xujw.dpdns.org/my' \
            -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36 Edg/137.0.0.0' \
            -H 'Accept: application/json, text/plain, */*' \
            -H 'sec-ch-ua: "Microsoft Edge";v="137", "Chromium";v="137", "Not/A)Brand";v="24"' \
            -H 'sec-ch-ua-mobile: ?0' \
            --fail
            # 如果你需要保存备份内容到文件: --output backup_data.json

          echo "调用 API 备份数据完成。"
